// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAznW5f86GAxJg540d1EHqHtTUq61JI6Es',
    appId: '1:808949934367:web:2c69b717582fcf1d09a82a',
    messagingSenderId: '808949934367',
    projectId: 'diaryproject-64b2c',
    authDomain: 'diaryproject-64b2c.firebaseapp.com',
    storageBucket: 'diaryproject-64b2c.appspot.com',
    measurementId: 'G-RH7VXQVCQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hmCm3EaGGmjFMWO2E3uc7Vhl0dwzaZk',
    appId: '1:808949934367:android:643ec4c0f6257c1009a82a',
    messagingSenderId: '808949934367',
    projectId: 'diaryproject-64b2c',
    storageBucket: 'diaryproject-64b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHpTgaRzc4L4VPFCX6U8qp4PeRqo0nqvg',
    appId: '1:808949934367:ios:ffc8f6cfa3b7032e09a82a',
    messagingSenderId: '808949934367',
    projectId: 'diaryproject-64b2c',
    storageBucket: 'diaryproject-64b2c.appspot.com',
    iosBundleId: 'com.example.emoDiaryProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHpTgaRzc4L4VPFCX6U8qp4PeRqo0nqvg',
    appId: '1:808949934367:ios:ffc8f6cfa3b7032e09a82a',
    messagingSenderId: '808949934367',
    projectId: 'diaryproject-64b2c',
    storageBucket: 'diaryproject-64b2c.appspot.com',
    iosBundleId: 'com.example.emoDiaryProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAznW5f86GAxJg540d1EHqHtTUq61JI6Es',
    appId: '1:808949934367:web:55cd1cb40b2a5d4209a82a',
    messagingSenderId: '808949934367',
    projectId: 'diaryproject-64b2c',
    authDomain: 'diaryproject-64b2c.firebaseapp.com',
    storageBucket: 'diaryproject-64b2c.appspot.com',
    measurementId: 'G-SGN791CWM5',
  );
}
